package com.zhangyue.we.x2c.layouts;

import android.content.Context;
import android.content.res.Resources;
import android.util.TypedValue;
import android.view.View;
import android.widget.TextView;
import androidx.constraintlayout.widget.ConstraintLayout;
import com.xiaomi.micolauncher.R;
import com.xiaomi.micolauncher.module.homepage.view.AppSelectedView;
import com.zhangyue.we.x2c.IViewCreator;

/* loaded from: classes4.dex */
public class X2C127_App_Selected_Layout implements IViewCreator {
    @Override // com.zhangyue.we.x2c.IViewCreator
    public View createView(Context context) {
        Resources resources = context.getResources();
        ConstraintLayout constraintLayout = new ConstraintLayout(context);
        constraintLayout.setLayoutParams(new ConstraintLayout.LayoutParams((int) resources.getDimension(R.dimen.app_selected_app_layout_width), (int) resources.getDimension(R.dimen.app_selected_app_layout_height)));
        constraintLayout.setPadding((int) resources.getDimension(R.dimen.app_selected_app_layout_margin_start), (int) resources.getDimension(R.dimen.app_selected_app_layout_margin_top), (int) resources.getDimension(R.dimen.app_selected_app_layout_margin_start), (int) resources.getDimension(R.dimen.app_selected_app_layout_margin_top));
        TextView textView = new TextView(context);
        ConstraintLayout.LayoutParams layoutParams = new ConstraintLayout.LayoutParams(-2, -2);
        textView.setId(R.id.tvTitle);
        textView.setText(R.string.title_app_hots);
        layoutParams.leftMargin = (int) resources.getDimension(R.dimen.app_selected_app_layout_margin_start);
        textView.setTextColor(resources.getColor(R.color.app_card_title_text_color));
        textView.setTextSize(0, resources.getDimension(R.dimen.app_card_title_text_size));
        layoutParams.startToStart = 0;
        layoutParams.topToTop = 0;
        layoutParams.validate();
        textView.setLayoutParams(layoutParams);
        constraintLayout.addView(textView);
        AppSelectedView appSelectedView = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams2 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView.setId(R.id.selected_app_first);
        layoutParams2.topMargin = (int) TypedValue.applyDimension(1, 12.0f, resources.getDisplayMetrics());
        layoutParams2.endToStart = R.id.selected_app_second;
        layoutParams2.startToStart = 0;
        layoutParams2.topToBottom = R.id.tvTitle;
        layoutParams2.validate();
        appSelectedView.setLayoutParams(layoutParams2);
        constraintLayout.addView(appSelectedView);
        AppSelectedView appSelectedView2 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams3 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView2.setId(R.id.selected_app_second);
        layoutParams3.endToStart = R.id.selected_app_third;
        layoutParams3.startToEnd = R.id.selected_app_first;
        layoutParams3.topToTop = R.id.selected_app_first;
        layoutParams3.validate();
        appSelectedView2.setLayoutParams(layoutParams3);
        constraintLayout.addView(appSelectedView2);
        AppSelectedView appSelectedView3 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams4 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView3.setId(R.id.selected_app_third);
        layoutParams4.endToEnd = 0;
        layoutParams4.startToEnd = R.id.selected_app_second;
        layoutParams4.topToTop = R.id.selected_app_first;
        layoutParams4.validate();
        appSelectedView3.setLayoutParams(layoutParams4);
        constraintLayout.addView(appSelectedView3);
        AppSelectedView appSelectedView4 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams5 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView4.setId(R.id.selected_app_fourth);
        layoutParams5.endToStart = R.id.selected_app_fifth;
        layoutParams5.startToStart = R.id.selected_app_first;
        layoutParams5.topToBottom = R.id.selected_app_first;
        layoutParams5.validate();
        appSelectedView4.setLayoutParams(layoutParams5);
        constraintLayout.addView(appSelectedView4);
        AppSelectedView appSelectedView5 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams6 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView5.setId(R.id.selected_app_fifth);
        layoutParams6.endToStart = R.id.selected_app_sixth;
        layoutParams6.startToEnd = R.id.selected_app_fourth;
        layoutParams6.topToTop = R.id.selected_app_fourth;
        layoutParams6.validate();
        appSelectedView5.setLayoutParams(layoutParams6);
        constraintLayout.addView(appSelectedView5);
        AppSelectedView appSelectedView6 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams7 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView6.setId(R.id.selected_app_sixth);
        layoutParams7.endToEnd = 0;
        layoutParams7.startToEnd = R.id.selected_app_fifth;
        layoutParams7.topToTop = R.id.selected_app_fourth;
        layoutParams7.validate();
        appSelectedView6.setLayoutParams(layoutParams7);
        constraintLayout.addView(appSelectedView6);
        AppSelectedView appSelectedView7 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams8 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView7.setId(R.id.selected_app_seventh);
        layoutParams8.endToStart = R.id.selected_app_eight;
        layoutParams8.startToStart = R.id.selected_app_first;
        layoutParams8.topToBottom = R.id.selected_app_fourth;
        layoutParams8.validate();
        appSelectedView7.setLayoutParams(layoutParams8);
        constraintLayout.addView(appSelectedView7);
        AppSelectedView appSelectedView8 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams9 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView8.setId(R.id.selected_app_eight);
        layoutParams9.endToStart = R.id.selected_app_ninth;
        layoutParams9.startToEnd = R.id.selected_app_seventh;
        layoutParams9.topToTop = R.id.selected_app_seventh;
        layoutParams9.validate();
        appSelectedView8.setLayoutParams(layoutParams9);
        constraintLayout.addView(appSelectedView8);
        AppSelectedView appSelectedView9 = new AppSelectedView(context);
        ConstraintLayout.LayoutParams layoutParams10 = new ConstraintLayout.LayoutParams(-2, -2);
        appSelectedView9.setId(R.id.selected_app_ninth);
        layoutParams10.endToEnd = 0;
        layoutParams10.startToEnd = R.id.selected_app_eight;
        layoutParams10.topToTop = R.id.selected_app_seventh;
        layoutParams10.validate();
        appSelectedView9.setLayoutParams(layoutParams10);
        constraintLayout.addView(appSelectedView9);
        return constraintLayout;
    }
}
