package com.xiaomi.micolauncher.skills.openplatform.controller.uievent;

/* loaded from: classes3.dex */
public class BluetoothControlAction {
    public EnumAction action;

    /* loaded from: classes3.dex */
    public enum EnumAction {
        ACTION_IDLE,
        ACTION_REQUEST_OPEN_BY_BT_BUTTON,
        ACTION_REQUEST_OPEN_BY_BT_BUTTON_DONE,
        ACTION_REQUEST_OPEN_BY_VOICE_QUERY,
        ACTION_REQUEST_OPEN_BY_VOICE_QUERY_DONE,
        ACTION_REQUEST_OPEN_BY_CODE,
        ACTION_REQUEST_OPEN_BY_CODE_DONE,
        ACTION_REQUEST_CLOSE_BY_BT_BUTTON,
        ACTION_REQUEST_CLOSE_BY_BT_BUTTON_DONE,
        ACTION_REQUEST_CLOSE_BY_CODE,
        ACTION_REQUEST_CLOSE_BY_CODE_DONE,
        ACTION_REQUEST_CLOSE_BY_WAIT_TIMEOUT,
        ACTION_REQUEST_CLOSE_BY_WAIT_TIMEOUT_DONE,
        ACTION_REQUEST_CLOSE_BY_VOICE_QUERY,
        ACTION_REQUEST_CLOSE_BY_VOICE_QUERY_DONE,
        ACTION_REQUEST_CONNECT_BY_ITEM_CLICK,
        ACTION_REQUEST_CONNECT_BY_ITEM_CLICK_DONE,
        ACTION_REQUEST_CONNECT_BY_VOICE_QUERY,
        ACTION_REQUEST_CONNECT_BY_VOICE_QUERY_DONE,
        ACTION_REQUEST_CONNECT_BY_CODE,
        ACTION_REQUEST_CONNECT_BY_CODE_DONE,
        ACTION_REQUEST_DISCONNECT_BY_ITEM_CLICK,
        ACTION_REQUEST_DISCONNECT_BY_ITEM_CLICK_DONE,
        ACTION_REQUEST_DISCONNECT_BY_VOICE_QUERY,
        ACTION_REQUEST_DISCONNECT_BY_VOICE_QUERY_DONE,
        ACTION_REQUEST_DISCONNECT_BY_CODE,
        ACTION_REQUEST_DISCONNECT_BY_CODE_DONE,
        ACTION_REQUEST_REMOVE_BONDED_BY_ITEM_CLICK,
        ACTION_REQUEST_REMOVE_BONDED_BY_ITEM_CLICK_DONE,
        ACTION_REQUEST_RECONNECT_BY_CONNECTION_TIMEOUT,
        ACTION_REQUEST_RECONNECT_BY_CONNECTION_TIMEOUT_DONE,
        ACTION_POST_UPDATE_VIEW,
        ACTION_POST_UPDATE_BT_NAME,
        ACTION_POST_NOTIFY_CHANGED,
        ACTION_REQUEST_OPEN_BY_BT_MESH,
        ACTION_REQUEST_OPEN_BY_BT_MESH_DONE
    }

    public BluetoothControlAction(EnumAction enumAction) {
        this.action = enumAction;
    }
}
